name: CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Replace with your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_model.py

      - name: Deploy application
        run: |
          chmod +x deploy.sh
          ./deploy.sh
        env:
          # Add any environment variables needed for deployment
        
          DEPLOY_ENV: ${{ secrets.DEPLOY_ENV }}

